fix(chore): fixing sonar smells
sourcefuse/loopback4-authentication pull request #149
Opened 2023-03-16 13:04 UTC by arpit1503khanna

## Description

resolving sonar smells to improve quality gate

Fixes # (GH-142)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2023-05-15 08:35 UTC, RaghavaroraSF commented on src/strategies/passport/passport-insta-oauth2/insta-auth-strategy-factory-provider.ts
> +    const func = async (
done

2023-05-15 08:36 UTC, RaghavaroraSF commented on src/strategies/passport/passport-google-oauth2/google-auth-strategy-factory-provider.ts
>          // eslint-disable-next-line @typescript-eslint/no-misused-promises
by removing this it gives error

2023-07-27 05:46 UTC, yeshamavani requested changes

2023-07-27 05:46 UTC, yeshamavani commented on src/strategies/passport/passport-apple-oauth2/apple-auth-strategy-factory-provider.ts
> +          decodedIdToken: string,
??

2023-11-22 15:16 UTC, closed without merging