fix(component): make passport packages optional
sourcefuse/loopback4-authentication pull request #156
Opened 2023-04-19 14:12 UTC by RaghavaroraSF

## Description

- All passport packages are made optional, and the user should install them only if required.

BREAKING CHANGE:
 - change import path for specific passport packages

Fixes # (GH-125)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2023-05-19 06:21 UTC, shubhamp-sf commented
Hi @RaghavaroraSF please include the repo link in the description of the repo in which you tested this change.

2023-11-07 15:01 UTC, yeshamavani commented
@karuneshsf picked this issue

2023-11-16 06:02 UTC, yeshamavani requested changes

2023-11-16 06:02 UTC, yeshamavani commented on README.md
> +In order to use it, run `npm install passport-google-oauth20` or `npm install @types/passport-google-oauth20`.
@karuneshsf

2023-11-16 10:18 UTC, yeshamavani commented
code smells

2023-11-21 09:50 UTC, yeshamavani approved these changes

2023-11-21 09:50 UTC, merged

2023-12-07 09:32 UTC, yeshamavani commented
:tada: This PR is included in version 11.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/loopback4-authentication/v/11.0.0)
- [GitHub release](https://github.com/sourcefuse/loopback4-authentication/releases/tag/v11.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: