refactor(component): make bearer strategy non optional
sourcefuse/loopback4-authentication pull request #210
Opened 2024-01-12 11:21 UTC by sf-sahil-jassal

make bearer strategy non optional,
resulting client password strategy also not optional

GH-209

## Description

Making the bearer strategy mandatory. But, by only making the bearer as manadatory, failed in test cases. Seems like, client password strategy is also needed for the same. So, I also made client password strategy as mandatory.

Fixes #209 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2024-01-15 13:15 UTC, yeshamavani requested changes

2024-01-15 13:15 UTC, yeshamavani commented on package.json
"./passport-bearer": {
      "type": "./dist/strategies/passport/passport-bearer/index.d.ts",
      "default": "./dist/strategies/passport/passport-bearer/index.js"
    },
    "./passport-client-password": {
      "type": "./dist/strategies/passport/passport-client-password/index.d.ts",
      "default": "./dist/strategies/passport/passport-client-password/index.js"


not needed should be directly exported from the package

2024-01-15 13:21 UTC, sf-sahil-jassal commented on package.json
ok

2024-01-17 14:28 UTC, merged

2024-01-17 16:54 UTC, yeshamavani commented
:tada: This PR is included in version 11.0.1 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/loopback4-authentication/v/11.0.1)
- [GitHub release](https://github.com/sourcefuse/loopback4-authentication/releases/tag/v11.0.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: