Facebookoauth
sourcefuse/loopback4-authentication pull request #47
Opened 2021-07-06 11:41 UTC by ashutosh-bansal-2136

## Description

Added facebook oauth authentication

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2021-07-06 11:46 UTC, akshatdubeysf commented
@ashutosh-bansal-2136 fix the PR title

2021-07-06 12:11 UTC, akshatdubeysf requested changes

2021-07-06 12:11 UTC, akshatdubeysf commented on src/strategies/passport/passport-facebook-oauth2/facebook-auth-strategy-factory-provider.ts
> +interface StratOptions extends StrategyOption {
Interface Name?

2021-07-06 12:16 UTC, akshatdubeysf commented on src/strategies/passport/passport-facebook-oauth2/facebook-auth-strategy-factory-provider.ts
> +interface StratOptions extends StrategyOption {
Does the interface from facebook-passport not have the passReqToCallback property?

2021-07-07 11:50 UTC, akshatdubeysf approved these changes

2021-07-07 13:17 UTC, samarpan-b approved these changes

2021-07-07 13:17 UTC, merged